### ISSUE TITLE
JDK 11 + required?

### ISSUE THREAD

**Issue by funyule** [jetty-project/jetty-load-base#94]
the jetty-load-generator-client classes has version 55.0 
is JDK11+ required ? 
is there any jdk8 version?

**Comment by joakime** [comment]
At the end of March 2022 Java 8 support transitions from Premier Support (and public releases of the JDK/JVM)
to Extended Support (with traditionally private releases of JDK/JVM).

If past behavior of Java is any indication, this is the final straw that kills open source support for that JVM.
Especially so with Open Source that depends on periodic public releases to satisfy the quickly changing SSL/TLS landscape.

https://endoflife.date/java
